title                       : The Turing Way  # The title of the book
author                      : The Turing Way Community  # The author of the book to be placed in the footer
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : "./figures/logo.png"  # A path to the book logo

html:
  favicon                   : "./figures/favicon-32x32.png"  # A path to a favicon image
  navbar_footer_text        :
    'Visit our <a href="https://github.com/alan-turing-institute/the-turing-way">GitHub Repository</a>
    <div>
    This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>'  # Will be displayed underneath the left navigation bar.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
